apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-lab
  labels:
    app: cloudops-lab
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloudops-lab
  template:
    metadata:
      labels:
        app: cloudops-lab
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: cloudops-lab:dev-001
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: LAB_ENV
              value: dev
            - name: LAB_MODE
              value: normal
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 192Mi
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 18
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 10001
